//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Retour
    {
        public long RetourId { get; set; }
        public Nullable<long> BatimentId { get; set; }
        public Nullable<long> LogementId { get; set; }
        public Nullable<long> MenageId { get; set; }
        public Nullable<long> DecesId { get; set; }
        public Nullable<long> EmigreId { get; set; }
        public Nullable<long> IndividuId { get; set; }
        public string SdeId { get; set; }
        public string DateRetour { get; set; }
        public string DateRetourEffectue { get; set; }
        public string Raison { get; set; }
        public string Statut { get; set; }
    }
}
