//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LogementCE
    {
        public long LogeId { get; set; }
        public Nullable<long> BatimentId { get; set; }
        public string SdeId { get; set; }
        public Nullable<long> QlCategLogement { get; set; }
        public Nullable<long> QlcTypeLogement { get; set; }
        public Nullable<long> Qllc2bTotalGarcon { get; set; }
        public Nullable<long> Qlc2bTotalFille { get; set; }
        public Nullable<long> Qlin1NumeroOrdre { get; set; }
        public Nullable<long> Qlin2StatutOccupation { get; set; }
        public Nullable<long> Qlin4TypeLogement { get; set; }
        public Nullable<long> Qlin5MateriauSol { get; set; }
        public Nullable<long> Qlin6NombrePiece { get; set; }
        public Nullable<long> Qlin7NbreChambreACoucher { get; set; }
        public Nullable<long> Qlin8NbreIndividuDepense { get; set; }
        public Nullable<long> Qlin9NbreTotalMenage { get; set; }
        public Nullable<long> Statut { get; set; }
        public Nullable<long> IsValidated { get; set; }
        public string DateDebutCollecte { get; set; }
        public string DateFinCollecte { get; set; }
        public Nullable<long> DureeSaisie { get; set; }
        public Nullable<long> IsContreEnqueteMade { get; set; }
    }
}
