//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RprtComparaison
    {
        public long RprtComparaisonId { get; set; }
        public Nullable<long> ContreEnqueteId { get; set; }
        public Nullable<long> IsRepPrincipalLienParenteChefMenageEgal { get; set; }
        public Nullable<long> IsRepPrincipalSexeEgal { get; set; }
        public Nullable<long> IsRepPrincipalAgeEgal { get; set; }
        public Nullable<long> IsChefMenageSexeEgal { get; set; }
        public Nullable<long> IsChefMenageAgeEgal { get; set; }
        public Nullable<long> IsChefMenageNiveauEtudeEgal { get; set; }
        public Nullable<long> IsChefMenageSituationActEgal { get; set; }
        public Nullable<long> IsQaf1aHandicapVoirEgal { get; set; }
        public Nullable<long> IsQaf2aHandicapEntendreEgal { get; set; }
        public Nullable<long> IsQaf3aHandicapSouvenirEgal { get; set; }
        public Nullable<long> IsQaf4aHandicapSoignerEgal { get; set; }
        public Nullable<long> IsQaf5aHandicapCommuniquerEgal { get; set; }
        public Nullable<long> EcartE1EstAlphabetisePlus15Ans { get; set; }
        public Nullable<long> EcartE2FrequentationScolaire { get; set; }
        public Nullable<long> EcartE5aNiveauEtudeSecondaire { get; set; }
        public Nullable<long> EcartE8FormationProfessionnelle { get; set; }
        public Nullable<long> EcartA4SecteurInstitutionnel { get; set; }
        public Nullable<long> EcartNbreFemmes15_49Ans { get; set; }
        public Nullable<long> EcartF1aNbreFemmes15_49AnsEnfantNeVivant { get; set; }
        public Nullable<long> EcartF2aNbreEnfantVivantDeclares { get; set; }
    }
}
