//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sde
    {
        public string SdeId { get; set; }
        public string CodeDistrict { get; set; }
        public Nullable<long> AgentId { get; set; }
        public string NoOrdre { get; set; }
        public Nullable<long> StatutContreEnquete { get; set; }
        public Nullable<long> StatutCollecte { get; set; }
        public Nullable<long> RaisonCouverture { get; set; }
        public Nullable<long> TotalBatCartographie { get; set; }
        public Nullable<long> TotalBatRecense { get; set; }
        public Nullable<long> TotalBatRecenseV { get; set; }
        public Nullable<long> TotalLogeCRecense { get; set; }
        public Nullable<long> TotalLogeCRecenseV { get; set; }
        public Nullable<long> TotalLogeIRecense { get; set; }
        public Nullable<long> TotalLogeIRecenseV { get; set; }
        public Nullable<long> TotalLogeIRecenseNV { get; set; }
        public Nullable<long> TotalLogeCOccupeRecense { get; set; }
        public Nullable<long> TotalLogeCOccupeRecenseV { get; set; }
        public Nullable<long> TotalLogeCOccupeRecenseNV { get; set; }
        public Nullable<long> TotalLogeCUsageTemporelRecense { get; set; }
        public Nullable<long> TotalLogeCUsageTemporelRecenseV { get; set; }
        public Nullable<long> TotalLogeCUsageTemporelRecenseNV { get; set; }
        public Nullable<long> TotalLogeCVideRecense { get; set; }
        public Nullable<long> TotalLogeCVideRecenseV { get; set; }
        public Nullable<long> TotalLogeCVideRecenseNV { get; set; }
        public Nullable<long> TotalLogeIOccupeRecense { get; set; }
        public Nullable<long> TotalLogeIOccupeRecenseV { get; set; }
        public Nullable<long> TotalLogeIOccupeRecenseNV { get; set; }
        public Nullable<long> TotalLogeIUsageTemporelRecense { get; set; }
        public Nullable<long> TotalLogeIUsageTemporelRecenseV { get; set; }
        public Nullable<long> TotalLogeIUsageTemporelRecenseNV { get; set; }
        public Nullable<long> TotalLogeIVideRecense { get; set; }
        public Nullable<long> TotalLogeIVideRecenseV { get; set; }
        public Nullable<long> TotalLogeIVideRecenseNV { get; set; }
        public Nullable<long> TotalMenageRecense { get; set; }
        public Nullable<long> TotalMenageRecenseV { get; set; }
        public Nullable<long> TotalMenageRecenseNV { get; set; }
        public Nullable<long> TotalMenageUnipersonnel { get; set; }
        public Nullable<long> TotalMenageDe6IndsEtPlus { get; set; }
        public Nullable<long> TotalIndRecense { get; set; }
        public Nullable<long> TotalIndRecenseV { get; set; }
        public Nullable<long> TotalIndRecenseNV { get; set; }
        public Nullable<long> TotalIndCRecense { get; set; }
        public Nullable<long> TotalIndCRecenseV { get; set; }
        public Nullable<long> TotalIndCRecenseNV { get; set; }
        public Nullable<long> TotalIndIRecense____ { get; set; }
        public Nullable<long> TotalIndIRecenseV____ { get; set; }
        public Nullable<long> TotalIndIRecenseNV____ { get; set; }
        public Nullable<long> TotalIndFRecense { get; set; }
        public Nullable<long> TotalIndFRecenseV { get; set; }
        public Nullable<long> TotalIndFRecenseNV { get; set; }
        public Nullable<long> TotalIndGRecense { get; set; }
        public Nullable<long> TotalIndGRecenseV { get; set; }
        public Nullable<long> TotalIndGRecenseNV { get; set; }
        public Nullable<long> TotalIndCFRecense { get; set; }
        public Nullable<long> TotalIndCFRecenseV { get; set; }
        public Nullable<long> TotalIndCFRecenseNV { get; set; }
        public Nullable<long> TotalIndCGRecense { get; set; }
        public Nullable<long> TotalIndCGRecenseV { get; set; }
        public Nullable<long> TotalIndCGRecenseNV { get; set; }
        public Nullable<long> TotalIndIFRecense { get; set; }
        public Nullable<long> TotalIndIFRecenseV { get; set; }
        public Nullable<long> TotalIndIFRecenseNV { get; set; }
        public Nullable<long> TotalIndIGRecense { get; set; }
        public Nullable<long> TotalIndIGRecenseV { get; set; }
        public Nullable<long> TotalIndIGRecenseNV { get; set; }
        public Nullable<long> TotalEnfantDeMoinsDe5Ans { get; set; }
        public Nullable<long> TotalIndividu18AnsEtPlus { get; set; }
        public Nullable<long> TotalIndividu10AnsEtPlus { get; set; }
        public Nullable<long> TotalIndividu65AnsEtPlus { get; set; }
        public Nullable<double> IndiceMasculinite { get; set; }
        public Nullable<long> TotalEmigreRecense { get; set; }
        public Nullable<long> TotalEmigreFRecense { get; set; }
        public Nullable<long> TotalEmigreGRecense { get; set; }
        public Nullable<long> TotalDecesRecense { get; set; }
        public Nullable<long> TotalDecesFRecense { get; set; }
        public Nullable<long> TotalDecesGRecense { get; set; }
        public Nullable<long> TotalBatRecenseParJour { get; set; }
        public Nullable<long> TotalLogeRecenseParJour { get; set; }
        public Nullable<long> TotalMenageRecenseParJour { get; set; }
        public Nullable<long> TotalIndRecenseParJour { get; set; }
        public Nullable<long> TotalBatRecenseParJourV { get; set; }
        public Nullable<long> TotalLogeRecenseParJourV { get; set; }
        public Nullable<long> TotalMenageRecenseParJourV { get; set; }
        public Nullable<long> TotalIndRecenseParJourV { get; set; }
        public Nullable<long> TotalBatRecenseParJourNV { get; set; }
        public Nullable<long> TotalLogeRecenseParJourNV { get; set; }
        public Nullable<long> TotalMenageRecenseParJourNV { get; set; }
        public Nullable<long> TotalIndRecenseParJourNV { get; set; }
    }
}
