//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Probleme
    {
        public long ProblemeId { get; set; }
        public string SdeId { get; set; }
        public Nullable<long> BatimentId { get; set; }
        public string Objet { get; set; }
        public string Domaine { get; set; }
        public string CodeQuestion { get; set; }
        public string Nature { get; set; }
        public string CreateDate { get; set; }
        public Nullable<long> Statut { get; set; }
    }
}
