//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sde
    {
        public string SdeId { get; set; }
        public string CodeDistrict { get; set; }
        public Nullable<long> AgentId { get; set; }
        public string NoOrdre { get; set; }
        public Nullable<long> StatutContreEnquete { get; set; }
        public Nullable<long> StatutCollecte { get; set; }
        public Nullable<long> RaisonCouverture { get; set; }
        public Nullable<long> TotalBatCartographie { get; set; }
        public Nullable<long> TotalBatRecense { get; set; }
        public Nullable<long> TotalLogeCRecense { get; set; }
        public Nullable<long> TotalLogeIRecense { get; set; }
        public Nullable<long> TotalMenageRecense { get; set; }
        public Nullable<long> TotalMenageUnipersonnel { get; set; }
        public Nullable<long> TotalIndRecense { get; set; }
        public Nullable<long> TotalEmigreRecense { get; set; }
        public Nullable<long> TotalDecesRecense { get; set; }
    }
}
