//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Questions
    {
        public string CodeQuestion { get; set; }
        public string Libelle { get; set; }
        public string NomObjet { get; set; }
        public string DetailsQuestion { get; set; }
        public string CodeCategorie { get; set; }
        public string NomChamps { get; set; }
        public Nullable<long> TypeQuestion { get; set; }
        public Nullable<long> ContrainteQuestion { get; set; }
        public Nullable<long> ValeurMaxParChiffre { get; set; }
        public Nullable<long> NbreCaratereMaximal { get; set; }
        public Nullable<long> EstSautReponse { get; set; }
        public string QPrecedent { get; set; }
        public string QSuivant { get; set; }
    }
}
