//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BatimentCE
    {
        public long BatimentId { get; set; }
        public string SdeId { get; set; }
        public string Qhabitation { get; set; }
        public string Qrec { get; set; }
        public string Qrgph { get; set; }
        public string Qadresse { get; set; }
        public string Qlocalite { get; set; }
        public Nullable<long> Qb1Etat { get; set; }
        public Nullable<long> Qb2Type { get; set; }
        public Nullable<long> Qb3NombreEtage { get; set; }
        public Nullable<long> Qb4MateriauMur { get; set; }
        public Nullable<long> Qb5MateriauToit { get; set; }
        public Nullable<long> Qb6StatutOccupation { get; set; }
        public Nullable<long> Qb7Utilisation1 { get; set; }
        public Nullable<long> Qb7Utilisation2 { get; set; }
        public Nullable<long> Qb8NbreLogeCollectif { get; set; }
        public Nullable<long> Qb8NbreLogeIndividuel { get; set; }
        public Nullable<long> Statut { get; set; }
        public Nullable<long> IsValidated { get; set; }
        public Nullable<long> IsSynchroToCentrale { get; set; }
        public string DateDebutCollecte { get; set; }
        public string DateFinCollecte { get; set; }
        public Nullable<long> DureeSaisie { get; set; }
        public Nullable<long> IsContreEnqueteMade { get; set; }
    }
}
