//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.SupEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ContreEnquete
    {
        public long ContreEnqueteId { get; set; }
        public Nullable<long> BatimentId { get; set; }
        public string CodeDistrict { get; set; }
        public string SdeId { get; set; }
        public string NomSuperviseur { get; set; }
        public string PrenomSuperviseur { get; set; }
        public Nullable<long> TypeContreEnquete { get; set; }
        public string DateDebut { get; set; }
        public string DateFin { get; set; }
        public Nullable<long> Raison { get; set; }
        public Nullable<long> Statut { get; set; }
    }
}
