//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.MobileEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_individu
    {
        public long individuId { get; set; }
        public Nullable<long> menageId { get; set; }
        public Nullable<long> logeId { get; set; }
        public Nullable<long> batimentId { get; set; }
        public string sdeId { get; set; }
        public Nullable<long> q1NoOrdre { get; set; }
        public string qp2APrenom { get; set; }
        public string qp2BNom { get; set; }
        public Nullable<long> qp3LienDeParente { get; set; }
        public Nullable<long> qp3HabiteDansMenage { get; set; }
        public Nullable<long> qp4Sexe { get; set; }
        public Nullable<long> qp5DateNaissanceJour { get; set; }
        public Nullable<long> qp5DateNaissanceMois { get; set; }
        public Nullable<long> Qp5DateNaissanceAnnee { get; set; }
        public Nullable<long> qp5bAge { get; set; }
        public Nullable<long> qp6religion { get; set; }
        public string qp6AutreReligion { get; set; }
        public Nullable<long> qp7Nationalite { get; set; }
        public string qp7PaysNationalite { get; set; }
        public Nullable<long> qp8MereEncoreVivante { get; set; }
        public Nullable<long> qp9EstPlusAge { get; set; }
        public Nullable<long> qp10LieuNaissance { get; set; }
        public string qp10CommuneNaissance { get; set; }
        public string qp10VqseNaissance { get; set; }
        public string qp10PaysNaissance { get; set; }
        public Nullable<long> qp11PeriodeResidence { get; set; }
        public Nullable<long> qp12DomicileAvantRecensement { get; set; }
        public string qp12CommuneDomicileAvantRecensement { get; set; }
        public string qp12VqseDomicileAvantRecensement { get; set; }
        public string qp12PaysDomicileAvantRecensement { get; set; }
        public Nullable<long> qe1EstAlphabetise { get; set; }
        public Nullable<long> qe2FreqentationScolaireOuUniv { get; set; }
        public Nullable<long> qe3typeEcoleOuUniv { get; set; }
        public Nullable<long> qe4aNiveauEtude { get; set; }
        public string qe4bDerniereClasseOUAneEtude { get; set; }
        public Nullable<long> qe5DiplomeUniversitaire { get; set; }
        public string qe6DomaineEtudeUniversitaire { get; set; }
        public Nullable<long> qaf1HandicapVoir { get; set; }
        public Nullable<long> qaf2HandicapEntendre { get; set; }
        public Nullable<long> qaf3HandicapMarcher { get; set; }
        public Nullable<long> qaf4HandicapSouvenir { get; set; }
        public Nullable<long> qaf5HandicapPourSeSoigner { get; set; }
        public Nullable<long> qaf6HandicapCommuniquer { get; set; }
        public Nullable<long> qt1PossessionTelCellulaire { get; set; }
        public Nullable<long> qt2UtilisationInternet { get; set; }
        public Nullable<long> qem1DejaVivreAutrePays { get; set; }
        public string qem1AutrePays { get; set; }
        public Nullable<long> qem2MoisRetour { get; set; }
        public Nullable<long> qem2AnneeRetour { get; set; }
        public Nullable<long> qsm1StatutMatrimonial { get; set; }
        public Nullable<long> qa1ActEconomiqueDerniereSemaine { get; set; }
        public Nullable<long> qa2ActAvoirDemele1 { get; set; }
        public Nullable<long> qa2ActDomestique2 { get; set; }
        public Nullable<long> qa2ActCultivateur3 { get; set; }
        public Nullable<long> qa2ActAiderParent4 { get; set; }
        public Nullable<long> qa2ActAutre5 { get; set; }
        public Nullable<long> qa3StatutEmploie { get; set; }
        public Nullable<long> qa4SecteurInstitutionnel { get; set; }
        public string qa5TypeBienProduitParEntreprise { get; set; }
        public string qa5PreciserTypeBienProduitParEntreprise { get; set; }
        public Nullable<long> qa6LieuActDerniereSemaine { get; set; }
        public Nullable<long> qa7FoncTravail { get; set; }
        public Nullable<long> qa8EntreprendreDemarcheTravail { get; set; }
        public Nullable<long> qa9VouloirTravailler { get; set; }
        public Nullable<long> qa10DisponibilitePourTravail { get; set; }
        public Nullable<long> qa11RecevoirTransfertArgent { get; set; }
        public Nullable<long> qf1aNbreEnfantNeVivantM { get; set; }
        public Nullable<long> qf1bNbreEnfantNeVivantF { get; set; }
        public Nullable<long> qf2aNbreEnfantVivantM { get; set; }
        public Nullable<long> qf2bNbreEnfantVivantF { get; set; }
        public Nullable<long> qf3DernierEnfantJour { get; set; }
        public Nullable<long> qf3DernierEnfantMois { get; set; }
        public Nullable<long> qf3DernierEnfantAnnee { get; set; }
        public Nullable<long> qf4DENeVivantVit { get; set; }
        public Nullable<long> statut { get; set; }
        public Nullable<long> isFieldAllFilled { get; set; }
        public string dateDebutCollecte { get; set; }
        public string dateFinCollecte { get; set; }
        public Nullable<long> dureeSaisie { get; set; }
        public Nullable<long> isContreEnqueteMade { get; set; }
        public string codeAgentRecenceur { get; set; }
        public Nullable<long> isVerified { get; set; }
    }
}
