//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsi.Rgph.DataAccess.Entities.MobileEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reponse
    {
        public string codeUniqueReponse { get; set; }
        public string codeReponse { get; set; }
        public string libelleReponse { get; set; }
    }
}
