//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ht.Ihsil.Rgph.App.Superviseur.entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menage
    {
        public long menageId { get; set; }
        public Nullable<long> logeId { get; set; }
        public Nullable<long> batimentId { get; set; }
        public string sdeId { get; set; }
        public Nullable<long> qm1NoOrdre { get; set; }
        public Nullable<long> qm2ModeJouissance { get; set; }
        public Nullable<long> qm3ModeObtentionLoge { get; set; }
        public Nullable<long> qm4aModeAprovEauABoire { get; set; }
        public Nullable<long> qm4aModeAprovEauAUsageCourant { get; set; }
        public Nullable<long> qm5SrcEnergieCuisson1 { get; set; }
        public Nullable<long> qm5SrcEnergieCuisson2 { get; set; }
        public Nullable<long> qm6TypeEclairage { get; set; }
        public Nullable<long> qm7ModeEvacDechet { get; set; }
        public Nullable<long> qm8NbreRadio1 { get; set; }
        public Nullable<long> qm8NbreTelevision2 { get; set; }
        public Nullable<long> qm8NbreRefrigerateur3 { get; set; }
        public Nullable<long> qm8NbreFouElectrique4 { get; set; }
        public Nullable<long> qm8NbreOrdinateur5 { get; set; }
        public Nullable<long> qm8NbreMotoBicyclette6 { get; set; }
        public Nullable<long> qm8NbreVoitureMachine7 { get; set; }
        public Nullable<long> qm8NbreBateau8 { get; set; }
        public Nullable<long> qm8NbrePanneauGeneratrice9 { get; set; }
        public Nullable<long> qm8NbreMilletChevalBourique10 { get; set; }
        public Nullable<long> qm8NbreBoeufVache11 { get; set; }
        public Nullable<long> qm8NbreCochonCabrit12 { get; set; }
        public Nullable<long> qm8NbreBeteVolaille13 { get; set; }
        public Nullable<long> qm9AvoirPersDomestique { get; set; }
        public Nullable<long> qm9TotalDomestiqueFille { get; set; }
        public Nullable<long> qm9TotalDomestiqueGarcon { get; set; }
        public Nullable<long> qm10TotalIndividuVivant { get; set; }
        public Nullable<long> qm11Emigration { get; set; }
        public Nullable<long> qm11NbreEmigre { get; set; }
        public Nullable<long> qm12Deces { get; set; }
        public Nullable<long> qm12NbreDecede { get; set; }
        public Nullable<long> statut { get; set; }
        public Nullable<long> isValidated { get; set; }
        public string dateDebutCollecte { get; set; }
        public string dateFinCollecte { get; set; }
        public Nullable<long> dureeSaisie { get; set; }
        public Nullable<long> isFieldAllFilled { get; set; }
        public Nullable<long> isContreEnqueteMade { get; set; }
    }
}
