//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace Ht.Ihsil.Rgph.App.Superviseur.Schema
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]

    public partial class ContreEnqueteType
    {
        private long batimentIdField;

        public long batimentId
        {
            get { return batimentIdField; }
            set { batimentIdField = value; }
        }
        private string codeDistrictField;

        public string codeDistrict
        {
            get { return codeDistrictField; }
            set { codeDistrictField = value; }
        }
        private string dateDebutField;

        public string dateDebut
        {
            get { return dateDebutField; }
            set { dateDebutField = value; }
        }
        private string dateFinField;

        public string dateFin
        {
            get { return dateFinField; }
            set { dateFinField = value; }
        }
        private string nomSuperviseurField;

        public string nomSuperviseur
        {
            get { return nomSuperviseurField; }
            set { nomSuperviseurField = value; }
        }
        private string prenomSuperviseurField;

        public string prenomSuperviseur
        {
            get { return prenomSuperviseurField; }
            set { prenomSuperviseurField = value; }
        }
        private int raisonField;

        public int raison
        {
            get { return raisonField; }
            set { raisonField = value; }
        }
        private string sdeIdField;

        public string sdeId
        {
            get { return sdeIdField; }
            set { sdeIdField = value; }
        }
        private int statutField;

        public int statut
        {
            get { return statutField; }
            set { statutField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema", IsNullable = false)]
    public partial class BatimentData
    {

        private string usernameField;

        private int dataTypeField;

        private BatimentType dataField;
        private ContreEnqueteType contreEnqueteField;

        public ContreEnqueteType contreEnquete
        {
            get { return contreEnqueteField; }
            set { contreEnqueteField = value; }
        }

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public int dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }

        /// <remarks/>
        public BatimentType data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class BatimentType
    {

        private long batimentIdField;

        private string deptIdField;

        private string comIdField;

        private string vqseIdField;

        private string sdeIdField;

        private short zoneField;

        private string disctrictIdField;

        private string qhabitationField;

        private string qlocaliteField;

        private string qadresseField;

        private string qrecField;

        private string qrgphField;

        private short qb1EtatField;

        private short qb2TypeField;

        private short qb3NombreEtageField;

        private short qb4MateriauMurField;

        private short qb5MateriauToitField;

        private short qb6StatutOccupationField;

        private short qb7Utilisation1Field;

        private short qb7Utilisation2Field;

        private short qb8NbreLogeCollectifField;

        private short qb8NbreLogeIndividuelField;

        private short statutField;

        private string dateEnvoiField;

        private bool isValidatedField;

        private bool isSynchroToAppSupField;

        private bool isSynchroToCentraleField;

        private string dateDebutCollecteField;

        private string dateFinCollecteField;

        private int dureeSaisieField;

        private bool isFieldAllFilledField;

        private bool isContreEnqueteMadeField;

        private string latitudeField;

        private string longitudeField;

        private string codeAgentRecenceurField;

        private LogementCType[] logementCsField;

        private LogementIType[] logementIsField;

        /// <remarks/>
        public long batimentId
        {
            get
            {
                return this.batimentIdField;
            }
            set
            {
                this.batimentIdField = value;
            }
        }

        /// <remarks/>
        public string deptId
        {
            get
            {
                return this.deptIdField;
            }
            set
            {
                this.deptIdField = value;
            }
        }

        /// <remarks/>
        public string comId
        {
            get
            {
                return this.comIdField;
            }
            set
            {
                this.comIdField = value;
            }
        }

        /// <remarks/>
        public string vqseId
        {
            get
            {
                return this.vqseIdField;
            }
            set
            {
                this.vqseIdField = value;
            }
        }

        /// <remarks/>
        public string sdeId
        {
            get
            {
                return this.sdeIdField;
            }
            set
            {
                this.sdeIdField = value;
            }
        }

        /// <remarks/>
        public short zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }

        /// <remarks/>
        public string disctrictId
        {
            get
            {
                return this.disctrictIdField;
            }
            set
            {
                this.disctrictIdField = value;
            }
        }

        /// <remarks/>
        public string qhabitation
        {
            get
            {
                return this.qhabitationField;
            }
            set
            {
                this.qhabitationField = value;
            }
        }

        /// <remarks/>
        public string qlocalite
        {
            get
            {
                return this.qlocaliteField;
            }
            set
            {
                this.qlocaliteField = value;
            }
        }

        /// <remarks/>
        public string qadresse
        {
            get
            {
                return this.qadresseField;
            }
            set
            {
                this.qadresseField = value;
            }
        }

        /// <remarks/>
        public string qrec
        {
            get
            {
                return this.qrecField;
            }
            set
            {
                this.qrecField = value;
            }
        }

        /// <remarks/>
        public string qrgph
        {
            get
            {
                return this.qrgphField;
            }
            set
            {
                this.qrgphField = value;
            }
        }

        /// <remarks/>
        public short qb1Etat
        {
            get
            {
                return this.qb1EtatField;
            }
            set
            {
                this.qb1EtatField = value;
            }
        }

        /// <remarks/>
        public short qb2Type
        {
            get
            {
                return this.qb2TypeField;
            }
            set
            {
                this.qb2TypeField = value;
            }
        }

        /// <remarks/>
        public short qb3NombreEtage
        {
            get
            {
                return this.qb3NombreEtageField;
            }
            set
            {
                this.qb3NombreEtageField = value;
            }
        }

        /// <remarks/>
        public short qb4MateriauMur
        {
            get
            {
                return this.qb4MateriauMurField;
            }
            set
            {
                this.qb4MateriauMurField = value;
            }
        }

        /// <remarks/>
        public short qb5MateriauToit
        {
            get
            {
                return this.qb5MateriauToitField;
            }
            set
            {
                this.qb5MateriauToitField = value;
            }
        }

        /// <remarks/>
        public short qb6StatutOccupation
        {
            get
            {
                return this.qb6StatutOccupationField;
            }
            set
            {
                this.qb6StatutOccupationField = value;
            }
        }

        /// <remarks/>
        public short qb7Utilisation1
        {
            get
            {
                return this.qb7Utilisation1Field;
            }
            set
            {
                this.qb7Utilisation1Field = value;
            }
        }

        /// <remarks/>
        public short qb7Utilisation2
        {
            get
            {
                return this.qb7Utilisation2Field;
            }
            set
            {
                this.qb7Utilisation2Field = value;
            }
        }

        /// <remarks/>
        public short qb8NbreLogeCollectif
        {
            get
            {
                return this.qb8NbreLogeCollectifField;
            }
            set
            {
                this.qb8NbreLogeCollectifField = value;
            }
        }

        /// <remarks/>
        public short qb8NbreLogeIndividuel
        {
            get
            {
                return this.qb8NbreLogeIndividuelField;
            }
            set
            {
                this.qb8NbreLogeIndividuelField = value;
            }
        }

        /// <remarks/>
        public short statut
        {
            get
            {
                return this.statutField;
            }
            set
            {
                this.statutField = value;
            }
        }

        /// <remarks/>
        public string dateEnvoi
        {
            get
            {
                return this.dateEnvoiField;
            }
            set
            {
                this.dateEnvoiField = value;
            }
        }

        /// <remarks/>
        public bool isValidated
        {
            get
            {
                return this.isValidatedField;
            }
            set
            {
                this.isValidatedField = value;
            }
        }

        /// <remarks/>
        public bool isSynchroToAppSup
        {
            get
            {
                return this.isSynchroToAppSupField;
            }
            set
            {
                this.isSynchroToAppSupField = value;
            }
        }

        /// <remarks/>
        public bool isSynchroToCentrale
        {
            get
            {
                return this.isSynchroToCentraleField;
            }
            set
            {
                this.isSynchroToCentraleField = value;
            }
        }

        /// <remarks/>
        public string dateDebutCollecte
        {
            get
            {
                return this.dateDebutCollecteField;
            }
            set
            {
                this.dateDebutCollecteField = value;
            }
        }

        /// <remarks/>
        public string dateFinCollecte
        {
            get
            {
                return this.dateFinCollecteField;
            }
            set
            {
                this.dateFinCollecteField = value;
            }
        }

        /// <remarks/>
        public int dureeSaisie
        {
            get
            {
                return this.dureeSaisieField;
            }
            set
            {
                this.dureeSaisieField = value;
            }
        }

        /// <remarks/>
        public bool isFieldAllFilled
        {
            get
            {
                return this.isFieldAllFilledField;
            }
            set
            {
                this.isFieldAllFilledField = value;
            }
        }

        /// <remarks/>
        public bool isContreEnqueteMade
        {
            get
            {
                return this.isContreEnqueteMadeField;
            }
            set
            {
                this.isContreEnqueteMadeField = value;
            }
        }

        /// <remarks/>
        public string latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        public string longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        public string codeAgentRecenceur
        {
            get
            {
                return this.codeAgentRecenceurField;
            }
            set
            {
                this.codeAgentRecenceurField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("logementCs")]
        public LogementCType[] logementCs
        {
            get
            {
                return this.logementCsField;
            }
            set
            {
                this.logementCsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("logementIs")]
        public LogementIType[] logementIs
        {
            get
            {
                return this.logementIsField;
            }
            set
            {
                this.logementIsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class LogementCType
    {

        private long logeIdField;

        private long batimentIdField;

        private string sdeIdField;

        private short qlCategLogementField;

        private short qlin1NumeroOrdreField;

        private short qlc1TypeLogementField;

        private short qllc2bTotalGarconField;

        private short qlc2bTotalFilleField;

        private short qlcTotalIndividusField;

        private short statutField;

        private bool isValidatedField;

        private string dateDebutCollecteField;

        private string dateFinCollecteField;

        private int dureeSaisieField;

        private bool isFieldAllFilledField;

        private bool isContreEnqueteMadeField;

        private short nbrTentativeField;

        private string codeAgentRecenceurField;

        private IndividuType[] individusField;

        /// <remarks/>
        public long logeId
        {
            get
            {
                return this.logeIdField;
            }
            set
            {
                this.logeIdField = value;
            }
        }

        /// <remarks/>
        public long batimentId
        {
            get
            {
                return this.batimentIdField;
            }
            set
            {
                this.batimentIdField = value;
            }
        }

        /// <remarks/>
        public string sdeId
        {
            get
            {
                return this.sdeIdField;
            }
            set
            {
                this.sdeIdField = value;
            }
        }

        /// <remarks/>
        public short qlCategLogement
        {
            get
            {
                return this.qlCategLogementField;
            }
            set
            {
                this.qlCategLogementField = value;
            }
        }

        /// <remarks/>
        public short qlin1NumeroOrdre
        {
            get
            {
                return this.qlin1NumeroOrdreField;
            }
            set
            {
                this.qlin1NumeroOrdreField = value;
            }
        }

        /// <remarks/>
        public short qlc1TypeLogement
        {
            get
            {
                return this.qlc1TypeLogementField;
            }
            set
            {
                this.qlc1TypeLogementField = value;
            }
        }

        /// <remarks/>
        public short qllc2bTotalGarcon
        {
            get
            {
                return this.qllc2bTotalGarconField;
            }
            set
            {
                this.qllc2bTotalGarconField = value;
            }
        }

        /// <remarks/>
        public short qlc2bTotalFille
        {
            get
            {
                return this.qlc2bTotalFilleField;
            }
            set
            {
                this.qlc2bTotalFilleField = value;
            }
        }

        /// <remarks/>
        public short qlcTotalIndividus
        {
            get
            {
                return this.qlcTotalIndividusField;
            }
            set
            {
                this.qlcTotalIndividusField = value;
            }
        }

        /// <remarks/>
        public short statut
        {
            get
            {
                return this.statutField;
            }
            set
            {
                this.statutField = value;
            }
        }

        /// <remarks/>
        public bool isValidated
        {
            get
            {
                return this.isValidatedField;
            }
            set
            {
                this.isValidatedField = value;
            }
        }

        /// <remarks/>
        public string dateDebutCollecte
        {
            get
            {
                return this.dateDebutCollecteField;
            }
            set
            {
                this.dateDebutCollecteField = value;
            }
        }

        /// <remarks/>
        public string dateFinCollecte
        {
            get
            {
                return this.dateFinCollecteField;
            }
            set
            {
                this.dateFinCollecteField = value;
            }
        }

        /// <remarks/>
        public int dureeSaisie
        {
            get
            {
                return this.dureeSaisieField;
            }
            set
            {
                this.dureeSaisieField = value;
            }
        }

        /// <remarks/>
        public bool isFieldAllFilled
        {
            get
            {
                return this.isFieldAllFilledField;
            }
            set
            {
                this.isFieldAllFilledField = value;
            }
        }

        /// <remarks/>
        public bool isContreEnqueteMade
        {
            get
            {
                return this.isContreEnqueteMadeField;
            }
            set
            {
                this.isContreEnqueteMadeField = value;
            }
        }

        /// <remarks/>
        public short nbrTentative
        {
            get
            {
                return this.nbrTentativeField;
            }
            set
            {
                this.nbrTentativeField = value;
            }
        }

        /// <remarks/>
        public string codeAgentRecenceur
        {
            get
            {
                return this.codeAgentRecenceurField;
            }
            set
            {
                this.codeAgentRecenceurField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("individus")]
        public IndividuType[] individus
        {
            get
            {
                return this.individusField;
            }
            set
            {
                this.individusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class IndividuType
    {

        private long individuIdField;

        private long menageIdField;

        private long logeIdField;

        private long batimentIdField;

        private string sdeIdField;

        private short q1NoOrdreField;

        private string q2NomField;

        private string q3PrenomField;

        private short q4SexeField;

        private short q5HabiteDansMenageField;

        private short q6LienDeParenteField;

        private short q7HabiteDansMenageField;

        private short q7DateNaissanceJourField;

        private short q7DateNaissanceMoisField;

        private int q7DateNaissanceAnneeField;

        private short q5bAgeField;

        private short qp6religionField;

        private string qp6AutreReligionField;

        private short qp7NationaliteField;

        private string qp7PaysNationaliteField;

        private short qp8MereEncoreVivanteField;

        private short qp9EstPlusAgeField;

        private short qp10LieuNaissanceField;

        private string qp10CommuneNaissanceField;

        private string qp10VqseNaissanceField;

        private string qp10PaysNaissanceField;

        private short qp11PeriodeResidenceField;

        private short qp12DomicileAvantRecensementField;

        private string qp12CommuneDomicileAvantRecensementField;

        private string qp12VqseDomicileAvantRecensementField;

        private string qp12PaysDomicileAvantRecensementField;

        private short qe1EstAlphabetiseField;

        private short qe2FreqentationScolaireOuUnivField;

        private short qe3typeEcoleOuUnivField;

        private short qe4aNiveauEtudeField;

        private string qe4bDerniereClasseOUAneEtudeField;

        private short qe5DiplomeUniversitaireField;

        private string qe6DomaineEtudeUniversitaireField;

        private short qaf1HandicapVoirField;

        private short qaf2HandicapEntendreField;

        private short qaf3HandicapMarcherField;

        private short qaf4HandicapSouvenirField;

        private short qaf5HandicapPourSeSoignerField;

        private short qaf6HandicapCommuniquerField;

        private short qt1PossessionTelCellulaireField;

        private short qt2UtilisationInternetField;

        private short qem1DejaVivreAutrePaysField;

        private string qem1AutrePaysField;

        private short qem2MoisRetourField;

        private int qem2AnneeRetourField;

        private short qsm1StatutMatrimonialField;

        private short qa1ActEconomiqueDerniereSemaineField;

        private short qa2ActAvoirDemele1Field;

        private short qa2ActDomestique2Field;

        private short qa2ActCultivateur3Field;

        private short qa2ActAiderParent4Field;

        private short qa2ActAutre5Field;

        private short qa3StatutEmploieField;

        private short qa4SecteurInstitutionnelField;

        private string qa5TypeBienProduitParEntrepriseField;

        private short qa6LieuActDerniereSemaineField;

        private short qa7FoncTravailField;

        private short qa8EntreprendreDemarcheTravailField;

        private short qa9VouloirTravaillerField;

        private short qa10DisponibilitePourTravailField;

        private short qa11RecevoirTransfertArgentField;

        private int qf1aNbreEnfantNeVivantMField;

        private int qf1bNbreEnfantNeVivantFField;

        private int qf2aNbreEnfantVivantMField;

        private int qf2bNbreEnfantVivantFField;

        private short qf3DernierEnfantJourField;

        private short qf3DernierEnfantMoisField;

        private int qf3DernierEnfantAnneeField;

        private short qf4DENeVivantVitField;

        private short statutField;

        private bool isFieldAllFilledField;

        private string dateDebutCollecteField;

        private string dateFinCollecteField;

        private int dureeSaisieField;

        private bool isContreEnqueteMadeField;

        private string codeAgentRecenceurField;

        /// <remarks/>
        public long individuId
        {
            get
            {
                return this.individuIdField;
            }
            set
            {
                this.individuIdField = value;
            }
        }

        /// <remarks/>
        public long menageId
        {
            get
            {
                return this.menageIdField;
            }
            set
            {
                this.menageIdField = value;
            }
        }

        /// <remarks/>
        public long logeId
        {
            get
            {
                return this.logeIdField;
            }
            set
            {
                this.logeIdField = value;
            }
        }

        /// <remarks/>
        public long batimentId
        {
            get
            {
                return this.batimentIdField;
            }
            set
            {
                this.batimentIdField = value;
            }
        }

        /// <remarks/>
        public string sdeId
        {
            get
            {
                return this.sdeIdField;
            }
            set
            {
                this.sdeIdField = value;
            }
        }

        /// <remarks/>
        public short q1NoOrdre
        {
            get
            {
                return this.q1NoOrdreField;
            }
            set
            {
                this.q1NoOrdreField = value;
            }
        }

        /// <remarks/>
        public string q2Nom
        {
            get
            {
                return this.q2NomField;
            }
            set
            {
                this.q2NomField = value;
            }
        }

        /// <remarks/>
        public string q3Prenom
        {
            get
            {
                return this.q3PrenomField;
            }
            set
            {
                this.q3PrenomField = value;
            }
        }

        /// <remarks/>
        public short q4Sexe
        {
            get
            {
                return this.q4SexeField;
            }
            set
            {
                this.q4SexeField = value;
            }
        }

        /// <remarks/>
        public short q5HabiteDansMenage
        {
            get
            {
                return this.q5HabiteDansMenageField;
            }
            set
            {
                this.q5HabiteDansMenageField = value;
            }
        }

        /// <remarks/>
        public short q6LienDeParente
        {
            get
            {
                return this.q6LienDeParenteField;
            }
            set
            {
                this.q6LienDeParenteField = value;
            }
        }

        /// <remarks/>
        public short q7HabiteDansMenage
        {
            get
            {
                return this.q7HabiteDansMenageField;
            }
            set
            {
                this.q7HabiteDansMenageField = value;
            }
        }

        /// <remarks/>
        public short q7DateNaissanceJour
        {
            get
            {
                return this.q7DateNaissanceJourField;
            }
            set
            {
                this.q7DateNaissanceJourField = value;
            }
        }

        /// <remarks/>
        public short q7DateNaissanceMois
        {
            get
            {
                return this.q7DateNaissanceMoisField;
            }
            set
            {
                this.q7DateNaissanceMoisField = value;
            }
        }

        /// <remarks/>
        public int q7DateNaissanceAnnee
        {
            get
            {
                return this.q7DateNaissanceAnneeField;
            }
            set
            {
                this.q7DateNaissanceAnneeField = value;
            }
        }

        /// <remarks/>
        public short q5bAge
        {
            get
            {
                return this.q5bAgeField;
            }
            set
            {
                this.q5bAgeField = value;
            }
        }

        /// <remarks/>
        public short qp6religion
        {
            get
            {
                return this.qp6religionField;
            }
            set
            {
                this.qp6religionField = value;
            }
        }

        /// <remarks/>
        public string qp6AutreReligion
        {
            get
            {
                return this.qp6AutreReligionField;
            }
            set
            {
                this.qp6AutreReligionField = value;
            }
        }

        /// <remarks/>
        public short qp7Nationalite
        {
            get
            {
                return this.qp7NationaliteField;
            }
            set
            {
                this.qp7NationaliteField = value;
            }
        }

        /// <remarks/>
        public string qp7PaysNationalite
        {
            get
            {
                return this.qp7PaysNationaliteField;
            }
            set
            {
                this.qp7PaysNationaliteField = value;
            }
        }

        /// <remarks/>
        public short qp8MereEncoreVivante
        {
            get
            {
                return this.qp8MereEncoreVivanteField;
            }
            set
            {
                this.qp8MereEncoreVivanteField = value;
            }
        }

        /// <remarks/>
        public short qp9EstPlusAge
        {
            get
            {
                return this.qp9EstPlusAgeField;
            }
            set
            {
                this.qp9EstPlusAgeField = value;
            }
        }

        /// <remarks/>
        public short qp10LieuNaissance
        {
            get
            {
                return this.qp10LieuNaissanceField;
            }
            set
            {
                this.qp10LieuNaissanceField = value;
            }
        }

        /// <remarks/>
        public string qp10CommuneNaissance
        {
            get
            {
                return this.qp10CommuneNaissanceField;
            }
            set
            {
                this.qp10CommuneNaissanceField = value;
            }
        }

        /// <remarks/>
        public string qp10VqseNaissance
        {
            get
            {
                return this.qp10VqseNaissanceField;
            }
            set
            {
                this.qp10VqseNaissanceField = value;
            }
        }

        /// <remarks/>
        public string qp10PaysNaissance
        {
            get
            {
                return this.qp10PaysNaissanceField;
            }
            set
            {
                this.qp10PaysNaissanceField = value;
            }
        }

        /// <remarks/>
        public short qp11PeriodeResidence
        {
            get
            {
                return this.qp11PeriodeResidenceField;
            }
            set
            {
                this.qp11PeriodeResidenceField = value;
            }
        }

        /// <remarks/>
        public short qp12DomicileAvantRecensement
        {
            get
            {
                return this.qp12DomicileAvantRecensementField;
            }
            set
            {
                this.qp12DomicileAvantRecensementField = value;
            }
        }

        /// <remarks/>
        public string qp12CommuneDomicileAvantRecensement
        {
            get
            {
                return this.qp12CommuneDomicileAvantRecensementField;
            }
            set
            {
                this.qp12CommuneDomicileAvantRecensementField = value;
            }
        }

        /// <remarks/>
        public string qp12VqseDomicileAvantRecensement
        {
            get
            {
                return this.qp12VqseDomicileAvantRecensementField;
            }
            set
            {
                this.qp12VqseDomicileAvantRecensementField = value;
            }
        }

        /// <remarks/>
        public string qp12PaysDomicileAvantRecensement
        {
            get
            {
                return this.qp12PaysDomicileAvantRecensementField;
            }
            set
            {
                this.qp12PaysDomicileAvantRecensementField = value;
            }
        }

        /// <remarks/>
        public short qe1EstAlphabetise
        {
            get
            {
                return this.qe1EstAlphabetiseField;
            }
            set
            {
                this.qe1EstAlphabetiseField = value;
            }
        }

        /// <remarks/>
        public short qe2FreqentationScolaireOuUniv
        {
            get
            {
                return this.qe2FreqentationScolaireOuUnivField;
            }
            set
            {
                this.qe2FreqentationScolaireOuUnivField = value;
            }
        }

        /// <remarks/>
        public short qe3typeEcoleOuUniv
        {
            get
            {
                return this.qe3typeEcoleOuUnivField;
            }
            set
            {
                this.qe3typeEcoleOuUnivField = value;
            }
        }

        /// <remarks/>
        public short qe4aNiveauEtude
        {
            get
            {
                return this.qe4aNiveauEtudeField;
            }
            set
            {
                this.qe4aNiveauEtudeField = value;
            }
        }

        /// <remarks/>
        public string qe4bDerniereClasseOUAneEtude
        {
            get
            {
                return this.qe4bDerniereClasseOUAneEtudeField;
            }
            set
            {
                this.qe4bDerniereClasseOUAneEtudeField = value;
            }
        }

        /// <remarks/>
        public short qe5DiplomeUniversitaire
        {
            get
            {
                return this.qe5DiplomeUniversitaireField;
            }
            set
            {
                this.qe5DiplomeUniversitaireField = value;
            }
        }

        /// <remarks/>
        public string qe6DomaineEtudeUniversitaire
        {
            get
            {
                return this.qe6DomaineEtudeUniversitaireField;
            }
            set
            {
                this.qe6DomaineEtudeUniversitaireField = value;
            }
        }

        /// <remarks/>
        public short qaf1HandicapVoir
        {
            get
            {
                return this.qaf1HandicapVoirField;
            }
            set
            {
                this.qaf1HandicapVoirField = value;
            }
        }

        /// <remarks/>
        public short qaf2HandicapEntendre
        {
            get
            {
                return this.qaf2HandicapEntendreField;
            }
            set
            {
                this.qaf2HandicapEntendreField = value;
            }
        }

        /// <remarks/>
        public short qaf3HandicapMarcher
        {
            get
            {
                return this.qaf3HandicapMarcherField;
            }
            set
            {
                this.qaf3HandicapMarcherField = value;
            }
        }

        /// <remarks/>
        public short qaf4HandicapSouvenir
        {
            get
            {
                return this.qaf4HandicapSouvenirField;
            }
            set
            {
                this.qaf4HandicapSouvenirField = value;
            }
        }

        /// <remarks/>
        public short qaf5HandicapPourSeSoigner
        {
            get
            {
                return this.qaf5HandicapPourSeSoignerField;
            }
            set
            {
                this.qaf5HandicapPourSeSoignerField = value;
            }
        }

        /// <remarks/>
        public short qaf6HandicapCommuniquer
        {
            get
            {
                return this.qaf6HandicapCommuniquerField;
            }
            set
            {
                this.qaf6HandicapCommuniquerField = value;
            }
        }

        /// <remarks/>
        public short qt1PossessionTelCellulaire
        {
            get
            {
                return this.qt1PossessionTelCellulaireField;
            }
            set
            {
                this.qt1PossessionTelCellulaireField = value;
            }
        }

        /// <remarks/>
        public short qt2UtilisationInternet
        {
            get
            {
                return this.qt2UtilisationInternetField;
            }
            set
            {
                this.qt2UtilisationInternetField = value;
            }
        }

        /// <remarks/>
        public short qem1DejaVivreAutrePays
        {
            get
            {
                return this.qem1DejaVivreAutrePaysField;
            }
            set
            {
                this.qem1DejaVivreAutrePaysField = value;
            }
        }

        /// <remarks/>
        public string qem1AutrePays
        {
            get
            {
                return this.qem1AutrePaysField;
            }
            set
            {
                this.qem1AutrePaysField = value;
            }
        }

        /// <remarks/>
        public short qem2MoisRetour
        {
            get
            {
                return this.qem2MoisRetourField;
            }
            set
            {
                this.qem2MoisRetourField = value;
            }
        }

        /// <remarks/>
        public int qem2AnneeRetour
        {
            get
            {
                return this.qem2AnneeRetourField;
            }
            set
            {
                this.qem2AnneeRetourField = value;
            }
        }

        /// <remarks/>
        public short qsm1StatutMatrimonial
        {
            get
            {
                return this.qsm1StatutMatrimonialField;
            }
            set
            {
                this.qsm1StatutMatrimonialField = value;
            }
        }

        /// <remarks/>
        public short qa1ActEconomiqueDerniereSemaine
        {
            get
            {
                return this.qa1ActEconomiqueDerniereSemaineField;
            }
            set
            {
                this.qa1ActEconomiqueDerniereSemaineField = value;
            }
        }

        /// <remarks/>
        public short qa2ActAvoirDemele1
        {
            get
            {
                return this.qa2ActAvoirDemele1Field;
            }
            set
            {
                this.qa2ActAvoirDemele1Field = value;
            }
        }

        /// <remarks/>
        public short qa2ActDomestique2
        {
            get
            {
                return this.qa2ActDomestique2Field;
            }
            set
            {
                this.qa2ActDomestique2Field = value;
            }
        }

        /// <remarks/>
        public short qa2ActCultivateur3
        {
            get
            {
                return this.qa2ActCultivateur3Field;
            }
            set
            {
                this.qa2ActCultivateur3Field = value;
            }
        }

        /// <remarks/>
        public short qa2ActAiderParent4
        {
            get
            {
                return this.qa2ActAiderParent4Field;
            }
            set
            {
                this.qa2ActAiderParent4Field = value;
            }
        }

        /// <remarks/>
        public short qa2ActAutre5
        {
            get
            {
                return this.qa2ActAutre5Field;
            }
            set
            {
                this.qa2ActAutre5Field = value;
            }
        }

        /// <remarks/>
        public short qa3StatutEmploie
        {
            get
            {
                return this.qa3StatutEmploieField;
            }
            set
            {
                this.qa3StatutEmploieField = value;
            }
        }

        /// <remarks/>
        public short qa4SecteurInstitutionnel
        {
            get
            {
                return this.qa4SecteurInstitutionnelField;
            }
            set
            {
                this.qa4SecteurInstitutionnelField = value;
            }
        }

        /// <remarks/>
        public string qa5TypeBienProduitParEntreprise
        {
            get
            {
                return this.qa5TypeBienProduitParEntrepriseField;
            }
            set
            {
                this.qa5TypeBienProduitParEntrepriseField = value;
            }
        }

        /// <remarks/>
        public short qa6LieuActDerniereSemaine
        {
            get
            {
                return this.qa6LieuActDerniereSemaineField;
            }
            set
            {
                this.qa6LieuActDerniereSemaineField = value;
            }
        }

        /// <remarks/>
        public short qa7FoncTravail
        {
            get
            {
                return this.qa7FoncTravailField;
            }
            set
            {
                this.qa7FoncTravailField = value;
            }
        }

        /// <remarks/>
        public short qa8EntreprendreDemarcheTravail
        {
            get
            {
                return this.qa8EntreprendreDemarcheTravailField;
            }
            set
            {
                this.qa8EntreprendreDemarcheTravailField = value;
            }
        }

        /// <remarks/>
        public short qa9VouloirTravailler
        {
            get
            {
                return this.qa9VouloirTravaillerField;
            }
            set
            {
                this.qa9VouloirTravaillerField = value;
            }
        }

        /// <remarks/>
        public short qa10DisponibilitePourTravail
        {
            get
            {
                return this.qa10DisponibilitePourTravailField;
            }
            set
            {
                this.qa10DisponibilitePourTravailField = value;
            }
        }

        /// <remarks/>
        public short qa11RecevoirTransfertArgent
        {
            get
            {
                return this.qa11RecevoirTransfertArgentField;
            }
            set
            {
                this.qa11RecevoirTransfertArgentField = value;
            }
        }

        /// <remarks/>
        public int qf1aNbreEnfantNeVivantM
        {
            get
            {
                return this.qf1aNbreEnfantNeVivantMField;
            }
            set
            {
                this.qf1aNbreEnfantNeVivantMField = value;
            }
        }

        /// <remarks/>
        public int qf1bNbreEnfantNeVivantF
        {
            get
            {
                return this.qf1bNbreEnfantNeVivantFField;
            }
            set
            {
                this.qf1bNbreEnfantNeVivantFField = value;
            }
        }

        /// <remarks/>
        public int qf2aNbreEnfantVivantM
        {
            get
            {
                return this.qf2aNbreEnfantVivantMField;
            }
            set
            {
                this.qf2aNbreEnfantVivantMField = value;
            }
        }

        /// <remarks/>
        public int qf2bNbreEnfantVivantF
        {
            get
            {
                return this.qf2bNbreEnfantVivantFField;
            }
            set
            {
                this.qf2bNbreEnfantVivantFField = value;
            }
        }

        /// <remarks/>
        public short qf3DernierEnfantJour
        {
            get
            {
                return this.qf3DernierEnfantJourField;
            }
            set
            {
                this.qf3DernierEnfantJourField = value;
            }
        }

        /// <remarks/>
        public short qf3DernierEnfantMois
        {
            get
            {
                return this.qf3DernierEnfantMoisField;
            }
            set
            {
                this.qf3DernierEnfantMoisField = value;
            }
        }

        /// <remarks/>
        public int qf3DernierEnfantAnnee
        {
            get
            {
                return this.qf3DernierEnfantAnneeField;
            }
            set
            {
                this.qf3DernierEnfantAnneeField = value;
            }
        }

        /// <remarks/>
        public short qf4DENeVivantVit
        {
            get
            {
                return this.qf4DENeVivantVitField;
            }
            set
            {
                this.qf4DENeVivantVitField = value;
            }
        }

        /// <remarks/>
        public short statut
        {
            get
            {
                return this.statutField;
            }
            set
            {
                this.statutField = value;
            }
        }

        /// <remarks/>
        public bool isFieldAllFilled
        {
            get
            {
                return this.isFieldAllFilledField;
            }
            set
            {
                this.isFieldAllFilledField = value;
            }
        }

        /// <remarks/>
        public string dateDebutCollecte
        {
            get
            {
                return this.dateDebutCollecteField;
            }
            set
            {
                this.dateDebutCollecteField = value;
            }
        }

        /// <remarks/>
        public string dateFinCollecte
        {
            get
            {
                return this.dateFinCollecteField;
            }
            set
            {
                this.dateFinCollecteField = value;
            }
        }

        /// <remarks/>
        public int dureeSaisie
        {
            get
            {
                return this.dureeSaisieField;
            }
            set
            {
                this.dureeSaisieField = value;
            }
        }

        /// <remarks/>
        public bool isContreEnqueteMade
        {
            get
            {
                return this.isContreEnqueteMadeField;
            }
            set
            {
                this.isContreEnqueteMadeField = value;
            }
        }

        /// <remarks/>
        public string codeAgentRecenceur
        {
            get
            {
                return this.codeAgentRecenceurField;
            }
            set
            {
                this.codeAgentRecenceurField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class RapportDeroulementCollecteType
    {

        private int detailsRapportIdField;

        private long rapportIdField;

        private short domaineField;

        private short sousDomaineField;

        private string problemeField;

        private short solutionField;

        private string precisionsField;

        private string suggestionsField;

        private string suiviField;

        /// <remarks/>
        public int detailsRapportId
        {
            get
            {
                return this.detailsRapportIdField;
            }
            set
            {
                this.detailsRapportIdField = value;
            }
        }

        /// <remarks/>
        public long rapportId
        {
            get
            {
                return this.rapportIdField;
            }
            set
            {
                this.rapportIdField = value;
            }
        }

        /// <remarks/>
        public short domaine
        {
            get
            {
                return this.domaineField;
            }
            set
            {
                this.domaineField = value;
            }
        }

        /// <remarks/>
        public short sousDomaine
        {
            get
            {
                return this.sousDomaineField;
            }
            set
            {
                this.sousDomaineField = value;
            }
        }

        /// <remarks/>
        public string probleme
        {
            get
            {
                return this.problemeField;
            }
            set
            {
                this.problemeField = value;
            }
        }

        /// <remarks/>
        public short solution
        {
            get
            {
                return this.solutionField;
            }
            set
            {
                this.solutionField = value;
            }
        }

        /// <remarks/>
        public string precisions
        {
            get
            {
                return this.precisionsField;
            }
            set
            {
                this.precisionsField = value;
            }
        }

        /// <remarks/>
        public string suggestions
        {
            get
            {
                return this.suggestionsField;
            }
            set
            {
                this.suggestionsField = value;
            }
        }

        /// <remarks/>
        public string suivi
        {
            get
            {
                return this.suiviField;
            }
            set
            {
                this.suiviField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class DecesType
    {

        private long decesIdField;

        private long menageIdField;

        private long logeIdField;

        private long batimentIdField;

        private string sdeIdField;

        private short qd2NoOrdreField;

        private short qd2aSexeField;

        private string qd2bAgeDecedeField;

        private short qd2c1CirconstanceDecesField;

        private short qd2c2CauseDecesField;

        private short statutField;

        private bool isFieldAllFilledField;

        private string dateDebutCollecteField;

        private string dateFinCollecteField;

        private int dureeSaisieField;

        private bool isContreEnqueteMadeField;

        private string codeAgentRecenceurField;

        /// <remarks/>
        public long decesId
        {
            get
            {
                return this.decesIdField;
            }
            set
            {
                this.decesIdField = value;
            }
        }

        /// <remarks/>
        public long menageId
        {
            get
            {
                return this.menageIdField;
            }
            set
            {
                this.menageIdField = value;
            }
        }

        /// <remarks/>
        public long logeId
        {
            get
            {
                return this.logeIdField;
            }
            set
            {
                this.logeIdField = value;
            }
        }

        /// <remarks/>
        public long batimentId
        {
            get
            {
                return this.batimentIdField;
            }
            set
            {
                this.batimentIdField = value;
            }
        }

        /// <remarks/>
        public string sdeId
        {
            get
            {
                return this.sdeIdField;
            }
            set
            {
                this.sdeIdField = value;
            }
        }

        /// <remarks/>
        public short qd2NoOrdre
        {
            get
            {
                return this.qd2NoOrdreField;
            }
            set
            {
                this.qd2NoOrdreField = value;
            }
        }

        /// <remarks/>
        public short qd2aSexe
        {
            get
            {
                return this.qd2aSexeField;
            }
            set
            {
                this.qd2aSexeField = value;
            }
        }

        /// <remarks/>
        public string qd2bAgeDecede
        {
            get
            {
                return this.qd2bAgeDecedeField;
            }
            set
            {
                this.qd2bAgeDecedeField = value;
            }
        }

        /// <remarks/>
        public short qd2c1CirconstanceDeces
        {
            get
            {
                return this.qd2c1CirconstanceDecesField;
            }
            set
            {
                this.qd2c1CirconstanceDecesField = value;
            }
        }

        /// <remarks/>
        public short qd2c2CauseDeces
        {
            get
            {
                return this.qd2c2CauseDecesField;
            }
            set
            {
                this.qd2c2CauseDecesField = value;
            }
        }

        /// <remarks/>
        public short statut
        {
            get
            {
                return this.statutField;
            }
            set
            {
                this.statutField = value;
            }
        }

        /// <remarks/>
        public bool isFieldAllFilled
        {
            get
            {
                return this.isFieldAllFilledField;
            }
            set
            {
                this.isFieldAllFilledField = value;
            }
        }

        /// <remarks/>
        public string dateDebutCollecte
        {
            get
            {
                return this.dateDebutCollecteField;
            }
            set
            {
                this.dateDebutCollecteField = value;
            }
        }

        /// <remarks/>
        public string dateFinCollecte
        {
            get
            {
                return this.dateFinCollecteField;
            }
            set
            {
                this.dateFinCollecteField = value;
            }
        }

        /// <remarks/>
        public int dureeSaisie
        {
            get
            {
                return this.dureeSaisieField;
            }
            set
            {
                this.dureeSaisieField = value;
            }
        }

        /// <remarks/>
        public bool isContreEnqueteMade
        {
            get
            {
                return this.isContreEnqueteMadeField;
            }
            set
            {
                this.isContreEnqueteMadeField = value;
            }
        }

        /// <remarks/>
        public string codeAgentRecenceur
        {
            get
            {
                return this.codeAgentRecenceurField;
            }
            set
            {
                this.codeAgentRecenceurField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class EmigreType
    {

        private long emigreIdField;

        private long menageIdField;

        private long logeIdField;

        private long batimentIdField;

        private string sdeIdField;

        private short qn1numeroOrdreField;

        private string qn2aNomCompletField;

        private short qn2bResidenceActuelleField;

        private short qn2cSexeField;

        private string qn2dAgeAuMomentDepartField;

        private short qn2eDernierPaysResidenceField;

        private short statutField;

        private bool isFieldAllFilledField;

        private string dateDebutCollecteField;

        private string dateFinCollecteField;

        private int dureeSaisieField;

        private string codeAgentRecenceurField;

        /// <remarks/>
        public long emigreId
        {
            get
            {
                return this.emigreIdField;
            }
            set
            {
                this.emigreIdField = value;
            }
        }

        /// <remarks/>
        public long menageId
        {
            get
            {
                return this.menageIdField;
            }
            set
            {
                this.menageIdField = value;
            }
        }

        /// <remarks/>
        public long logeId
        {
            get
            {
                return this.logeIdField;
            }
            set
            {
                this.logeIdField = value;
            }
        }

        /// <remarks/>
        public long batimentId
        {
            get
            {
                return this.batimentIdField;
            }
            set
            {
                this.batimentIdField = value;
            }
        }

        /// <remarks/>
        public string sdeId
        {
            get
            {
                return this.sdeIdField;
            }
            set
            {
                this.sdeIdField = value;
            }
        }

        /// <remarks/>
        public short qn1numeroOrdre
        {
            get
            {
                return this.qn1numeroOrdreField;
            }
            set
            {
                this.qn1numeroOrdreField = value;
            }
        }

        /// <remarks/>
        public string qn2aNomComplet
        {
            get
            {
                return this.qn2aNomCompletField;
            }
            set
            {
                this.qn2aNomCompletField = value;
            }
        }

        /// <remarks/>
        public short qn2bResidenceActuelle
        {
            get
            {
                return this.qn2bResidenceActuelleField;
            }
            set
            {
                this.qn2bResidenceActuelleField = value;
            }
        }

        /// <remarks/>
        public short qn2cSexe
        {
            get
            {
                return this.qn2cSexeField;
            }
            set
            {
                this.qn2cSexeField = value;
            }
        }

        /// <remarks/>
        public string qn2dAgeAuMomentDepart
        {
            get
            {
                return this.qn2dAgeAuMomentDepartField;
            }
            set
            {
                this.qn2dAgeAuMomentDepartField = value;
            }
        }

        /// <remarks/>
        public short qn2eDernierPaysResidence
        {
            get
            {
                return this.qn2eDernierPaysResidenceField;
            }
            set
            {
                this.qn2eDernierPaysResidenceField = value;
            }
        }

        /// <remarks/>
        public short statut
        {
            get
            {
                return this.statutField;
            }
            set
            {
                this.statutField = value;
            }
        }

        /// <remarks/>
        public bool isFieldAllFilled
        {
            get
            {
                return this.isFieldAllFilledField;
            }
            set
            {
                this.isFieldAllFilledField = value;
            }
        }

        /// <remarks/>
        public string dateDebutCollecte
        {
            get
            {
                return this.dateDebutCollecteField;
            }
            set
            {
                this.dateDebutCollecteField = value;
            }
        }

        /// <remarks/>
        public string dateFinCollecte
        {
            get
            {
                return this.dateFinCollecteField;
            }
            set
            {
                this.dateFinCollecteField = value;
            }
        }

        /// <remarks/>
        public int dureeSaisie
        {
            get
            {
                return this.dureeSaisieField;
            }
            set
            {
                this.dureeSaisieField = value;
            }
        }

        /// <remarks/>
        public string codeAgentRecenceur
        {
            get
            {
                return this.codeAgentRecenceurField;
            }
            set
            {
                this.codeAgentRecenceurField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class MenageType
    {

        private long menageIdField;

        private long logeIdField;

        private long batimentIdField;

        private string sdeIdField;

        private short qm1NoOrdreField;

        private short qm2ModeJouissanceField;

        private short qm3ModeObtentionLogeField;

        private short qm4_1ModeAprovEauABoireField;

        private short qm4_2ModeAprovEauAUsageCourantField;

        private short qm5SrcEnergieCuisson1Field;

        private short qm5SrcEnergieCuisson2Field;

        private short qm6TypeEclairageField;

        private short qm7ModeEvacDechetField;

        private short qm8EndroitBesoinPhysiologiqueField;

        private int qm9NbreRadio1Field;

        private int qm9NbreTelevision2Field;

        private int qm9NbreRefrigerateur3Field;

        private int qm9NbreFouElectrique4Field;

        private int qm9NbreOrdinateur5Field;

        private int qm9NbreMotoBicyclette6Field;

        private int qm9NbreVoitureMachine7Field;

        private int qm9NbreBateau8Field;

        private int qm9NbrePanneauGeneratrice9Field;

        private int qm9NbreMilletChevalBourique10Field;

        private int qm9NbreBoeufVache11Field;

        private int qm9NbreCochonCabrit12Field;

        private int qm9NbreBeteVolaille13Field;

        private short qm10AvoirPersDomestiqueField;

        private short qm10TotalDomestiqueFilleField;

        private short qm10TotalDomestiqueGarconField;

        private int qm11TotalIndividuVivantField;

        private short qn1EmigrationField;

        private short qn1NbreEmigreFilleField;

        private short qn1NbreEmigreGarconField;

        private short qd1DecesField;

        private short qd1NbreDecedeFilleField;

        private short qd1NbreDecedeGarconField;

        private short statutField;

        private bool isValidatedField;

        private string dateDebutCollecteField;

        private string dateFinCollecteField;

        private int dureeSaisieField;

        private bool isFieldAllFilledField;

        private bool isContreEnqueteMadeField;

        private string codeAgentRecenceurField;

        private EmigreType[] emigresField;

        private DecesType[] decesField;

        private IndividuType[] individusField;

        /// <remarks/>
        public long menageId
        {
            get
            {
                return this.menageIdField;
            }
            set
            {
                this.menageIdField = value;
            }
        }

        /// <remarks/>
        public long logeId
        {
            get
            {
                return this.logeIdField;
            }
            set
            {
                this.logeIdField = value;
            }
        }

        /// <remarks/>
        public long batimentId
        {
            get
            {
                return this.batimentIdField;
            }
            set
            {
                this.batimentIdField = value;
            }
        }

        /// <remarks/>
        public string sdeId
        {
            get
            {
                return this.sdeIdField;
            }
            set
            {
                this.sdeIdField = value;
            }
        }

        /// <remarks/>
        public short qm1NoOrdre
        {
            get
            {
                return this.qm1NoOrdreField;
            }
            set
            {
                this.qm1NoOrdreField = value;
            }
        }

        /// <remarks/>
        public short qm2ModeJouissance
        {
            get
            {
                return this.qm2ModeJouissanceField;
            }
            set
            {
                this.qm2ModeJouissanceField = value;
            }
        }

        /// <remarks/>
        public short qm3ModeObtentionLoge
        {
            get
            {
                return this.qm3ModeObtentionLogeField;
            }
            set
            {
                this.qm3ModeObtentionLogeField = value;
            }
        }

        /// <remarks/>
        public short qm4_1ModeAprovEauABoire
        {
            get
            {
                return this.qm4_1ModeAprovEauABoireField;
            }
            set
            {
                this.qm4_1ModeAprovEauABoireField = value;
            }
        }

        /// <remarks/>
        public short qm4_2ModeAprovEauAUsageCourant
        {
            get
            {
                return this.qm4_2ModeAprovEauAUsageCourantField;
            }
            set
            {
                this.qm4_2ModeAprovEauAUsageCourantField = value;
            }
        }

        /// <remarks/>
        public short qm5SrcEnergieCuisson1
        {
            get
            {
                return this.qm5SrcEnergieCuisson1Field;
            }
            set
            {
                this.qm5SrcEnergieCuisson1Field = value;
            }
        }

        /// <remarks/>
        public short qm5SrcEnergieCuisson2
        {
            get
            {
                return this.qm5SrcEnergieCuisson2Field;
            }
            set
            {
                this.qm5SrcEnergieCuisson2Field = value;
            }
        }

        /// <remarks/>
        public short qm6TypeEclairage
        {
            get
            {
                return this.qm6TypeEclairageField;
            }
            set
            {
                this.qm6TypeEclairageField = value;
            }
        }

        /// <remarks/>
        public short qm7ModeEvacDechet
        {
            get
            {
                return this.qm7ModeEvacDechetField;
            }
            set
            {
                this.qm7ModeEvacDechetField = value;
            }
        }

        /// <remarks/>
        public short qm8EndroitBesoinPhysiologique
        {
            get
            {
                return this.qm8EndroitBesoinPhysiologiqueField;
            }
            set
            {
                this.qm8EndroitBesoinPhysiologiqueField = value;
            }
        }

        /// <remarks/>
        public int qm9NbreRadio1
        {
            get
            {
                return this.qm9NbreRadio1Field;
            }
            set
            {
                this.qm9NbreRadio1Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreTelevision2
        {
            get
            {
                return this.qm9NbreTelevision2Field;
            }
            set
            {
                this.qm9NbreTelevision2Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreRefrigerateur3
        {
            get
            {
                return this.qm9NbreRefrigerateur3Field;
            }
            set
            {
                this.qm9NbreRefrigerateur3Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreFouElectrique4
        {
            get
            {
                return this.qm9NbreFouElectrique4Field;
            }
            set
            {
                this.qm9NbreFouElectrique4Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreOrdinateur5
        {
            get
            {
                return this.qm9NbreOrdinateur5Field;
            }
            set
            {
                this.qm9NbreOrdinateur5Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreMotoBicyclette6
        {
            get
            {
                return this.qm9NbreMotoBicyclette6Field;
            }
            set
            {
                this.qm9NbreMotoBicyclette6Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreVoitureMachine7
        {
            get
            {
                return this.qm9NbreVoitureMachine7Field;
            }
            set
            {
                this.qm9NbreVoitureMachine7Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreBateau8
        {
            get
            {
                return this.qm9NbreBateau8Field;
            }
            set
            {
                this.qm9NbreBateau8Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbrePanneauGeneratrice9
        {
            get
            {
                return this.qm9NbrePanneauGeneratrice9Field;
            }
            set
            {
                this.qm9NbrePanneauGeneratrice9Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreMilletChevalBourique10
        {
            get
            {
                return this.qm9NbreMilletChevalBourique10Field;
            }
            set
            {
                this.qm9NbreMilletChevalBourique10Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreBoeufVache11
        {
            get
            {
                return this.qm9NbreBoeufVache11Field;
            }
            set
            {
                this.qm9NbreBoeufVache11Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreCochonCabrit12
        {
            get
            {
                return this.qm9NbreCochonCabrit12Field;
            }
            set
            {
                this.qm9NbreCochonCabrit12Field = value;
            }
        }

        /// <remarks/>
        public int qm9NbreBeteVolaille13
        {
            get
            {
                return this.qm9NbreBeteVolaille13Field;
            }
            set
            {
                this.qm9NbreBeteVolaille13Field = value;
            }
        }

        /// <remarks/>
        public short qm10AvoirPersDomestique
        {
            get
            {
                return this.qm10AvoirPersDomestiqueField;
            }
            set
            {
                this.qm10AvoirPersDomestiqueField = value;
            }
        }

        /// <remarks/>
        public short qm10TotalDomestiqueFille
        {
            get
            {
                return this.qm10TotalDomestiqueFilleField;
            }
            set
            {
                this.qm10TotalDomestiqueFilleField = value;
            }
        }

        /// <remarks/>
        public short qm10TotalDomestiqueGarcon
        {
            get
            {
                return this.qm10TotalDomestiqueGarconField;
            }
            set
            {
                this.qm10TotalDomestiqueGarconField = value;
            }
        }

        /// <remarks/>
        public int qm11TotalIndividuVivant
        {
            get
            {
                return this.qm11TotalIndividuVivantField;
            }
            set
            {
                this.qm11TotalIndividuVivantField = value;
            }
        }

        /// <remarks/>
        public short qn1Emigration
        {
            get
            {
                return this.qn1EmigrationField;
            }
            set
            {
                this.qn1EmigrationField = value;
            }
        }

        /// <remarks/>
        public short qn1NbreEmigreFille
        {
            get
            {
                return this.qn1NbreEmigreFilleField;
            }
            set
            {
                this.qn1NbreEmigreFilleField = value;
            }
        }

        /// <remarks/>
        public short qn1NbreEmigreGarcon
        {
            get
            {
                return this.qn1NbreEmigreGarconField;
            }
            set
            {
                this.qn1NbreEmigreGarconField = value;
            }
        }

        /// <remarks/>
        public short qd1Deces
        {
            get
            {
                return this.qd1DecesField;
            }
            set
            {
                this.qd1DecesField = value;
            }
        }

        /// <remarks/>
        public short qd1NbreDecedeFille
        {
            get
            {
                return this.qd1NbreDecedeFilleField;
            }
            set
            {
                this.qd1NbreDecedeFilleField = value;
            }
        }

        /// <remarks/>
        public short qd1NbreDecedeGarcon
        {
            get
            {
                return this.qd1NbreDecedeGarconField;
            }
            set
            {
                this.qd1NbreDecedeGarconField = value;
            }
        }

        /// <remarks/>
        public short statut
        {
            get
            {
                return this.statutField;
            }
            set
            {
                this.statutField = value;
            }
        }

        /// <remarks/>
        public bool isValidated
        {
            get
            {
                return this.isValidatedField;
            }
            set
            {
                this.isValidatedField = value;
            }
        }

        /// <remarks/>
        public string dateDebutCollecte
        {
            get
            {
                return this.dateDebutCollecteField;
            }
            set
            {
                this.dateDebutCollecteField = value;
            }
        }

        /// <remarks/>
        public string dateFinCollecte
        {
            get
            {
                return this.dateFinCollecteField;
            }
            set
            {
                this.dateFinCollecteField = value;
            }
        }

        /// <remarks/>
        public int dureeSaisie
        {
            get
            {
                return this.dureeSaisieField;
            }
            set
            {
                this.dureeSaisieField = value;
            }
        }

        /// <remarks/>
        public bool isFieldAllFilled
        {
            get
            {
                return this.isFieldAllFilledField;
            }
            set
            {
                this.isFieldAllFilledField = value;
            }
        }

        /// <remarks/>
        public bool isContreEnqueteMade
        {
            get
            {
                return this.isContreEnqueteMadeField;
            }
            set
            {
                this.isContreEnqueteMadeField = value;
            }
        }

        /// <remarks/>
        public string codeAgentRecenceur
        {
            get
            {
                return this.codeAgentRecenceurField;
            }
            set
            {
                this.codeAgentRecenceurField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emigres")]
        public EmigreType[] emigres
        {
            get
            {
                return this.emigresField;
            }
            set
            {
                this.emigresField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deces")]
        public DecesType[] deces
        {
            get
            {
                return this.decesField;
            }
            set
            {
                this.decesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("individus")]
        public IndividuType[] individus
        {
            get
            {
                return this.individusField;
            }
            set
            {
                this.individusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    public partial class LogementIType
    {

        private long logeIdField;

        private long batimentIdField;

        private string sdeIdField;

        private short qlCategLogementField;

        private short qlin1NumeroOrdreField;

        private short qlc1TypeLogementField;

        private short qllc2bTotalGarconField;

        private short qlc2bTotalFilleField;

        private short qlcTotalIndividusField;

        private short qlin2StatutOccupationField;

        private short qlin3ExistenceLogementField;

        private short qlin4TypeLogementField;

        private short qlin5MateriauSolField;

        private short qlin6NombrePieceField;

        private short qlin7NbreChambreACoucherField;

        private short qlin8NbreIndividuDepenseField;

        private short qlin9NbreTotalMenageField;

        private short statutField;

        private bool isValidatedField;

        private string dateDebutCollecteField;

        private string dateFinCollecteField;

        private int dureeSaisieField;

        private bool isFieldAllFilledField;

        private bool isContreEnqueteMadeField;

        private short nbrTentativeField;

        private string codeAgentRecenceurField;

        private MenageType[] menagesField;

        /// <remarks/>
        public long logeId
        {
            get
            {
                return this.logeIdField;
            }
            set
            {
                this.logeIdField = value;
            }
        }

        /// <remarks/>
        public long batimentId
        {
            get
            {
                return this.batimentIdField;
            }
            set
            {
                this.batimentIdField = value;
            }
        }

        /// <remarks/>
        public string sdeId
        {
            get
            {
                return this.sdeIdField;
            }
            set
            {
                this.sdeIdField = value;
            }
        }

        /// <remarks/>
        public short qlCategLogement
        {
            get
            {
                return this.qlCategLogementField;
            }
            set
            {
                this.qlCategLogementField = value;
            }
        }

        /// <remarks/>
        public short qlin1NumeroOrdre
        {
            get
            {
                return this.qlin1NumeroOrdreField;
            }
            set
            {
                this.qlin1NumeroOrdreField = value;
            }
        }

        /// <remarks/>
        public short qlc1TypeLogement
        {
            get
            {
                return this.qlc1TypeLogementField;
            }
            set
            {
                this.qlc1TypeLogementField = value;
            }
        }

        /// <remarks/>
        public short qllc2bTotalGarcon
        {
            get
            {
                return this.qllc2bTotalGarconField;
            }
            set
            {
                this.qllc2bTotalGarconField = value;
            }
        }

        /// <remarks/>
        public short qlc2bTotalFille
        {
            get
            {
                return this.qlc2bTotalFilleField;
            }
            set
            {
                this.qlc2bTotalFilleField = value;
            }
        }

        /// <remarks/>
        public short qlcTotalIndividus
        {
            get
            {
                return this.qlcTotalIndividusField;
            }
            set
            {
                this.qlcTotalIndividusField = value;
            }
        }

        /// <remarks/>
        public short qlin2StatutOccupation
        {
            get
            {
                return this.qlin2StatutOccupationField;
            }
            set
            {
                this.qlin2StatutOccupationField = value;
            }
        }

        /// <remarks/>
        public short qlin3ExistenceLogement
        {
            get
            {
                return this.qlin3ExistenceLogementField;
            }
            set
            {
                this.qlin3ExistenceLogementField = value;
            }
        }

        /// <remarks/>
        public short qlin4TypeLogement
        {
            get
            {
                return this.qlin4TypeLogementField;
            }
            set
            {
                this.qlin4TypeLogementField = value;
            }
        }

        /// <remarks/>
        public short qlin5MateriauSol
        {
            get
            {
                return this.qlin5MateriauSolField;
            }
            set
            {
                this.qlin5MateriauSolField = value;
            }
        }

        /// <remarks/>
        public short qlin6NombrePiece
        {
            get
            {
                return this.qlin6NombrePieceField;
            }
            set
            {
                this.qlin6NombrePieceField = value;
            }
        }

        /// <remarks/>
        public short qlin7NbreChambreACoucher
        {
            get
            {
                return this.qlin7NbreChambreACoucherField;
            }
            set
            {
                this.qlin7NbreChambreACoucherField = value;
            }
        }

        /// <remarks/>
        public short qlin8NbreIndividuDepense
        {
            get
            {
                return this.qlin8NbreIndividuDepenseField;
            }
            set
            {
                this.qlin8NbreIndividuDepenseField = value;
            }
        }

        /// <remarks/>
        public short qlin9NbreTotalMenage
        {
            get
            {
                return this.qlin9NbreTotalMenageField;
            }
            set
            {
                this.qlin9NbreTotalMenageField = value;
            }
        }

        /// <remarks/>
        public short statut
        {
            get
            {
                return this.statutField;
            }
            set
            {
                this.statutField = value;
            }
        }

        /// <remarks/>
        public bool isValidated
        {
            get
            {
                return this.isValidatedField;
            }
            set
            {
                this.isValidatedField = value;
            }
        }

        /// <remarks/>
        public string dateDebutCollecte
        {
            get
            {
                return this.dateDebutCollecteField;
            }
            set
            {
                this.dateDebutCollecteField = value;
            }
        }

        /// <remarks/>
        public string dateFinCollecte
        {
            get
            {
                return this.dateFinCollecteField;
            }
            set
            {
                this.dateFinCollecteField = value;
            }
        }

        /// <remarks/>
        public int dureeSaisie
        {
            get
            {
                return this.dureeSaisieField;
            }
            set
            {
                this.dureeSaisieField = value;
            }
        }

        /// <remarks/>
        public bool isFieldAllFilled
        {
            get
            {
                return this.isFieldAllFilledField;
            }
            set
            {
                this.isFieldAllFilledField = value;
            }
        }

        /// <remarks/>
        public bool isContreEnqueteMade
        {
            get
            {
                return this.isContreEnqueteMadeField;
            }
            set
            {
                this.isContreEnqueteMadeField = value;
            }
        }

        /// <remarks/>
        public short nbrTentative
        {
            get
            {
                return this.nbrTentativeField;
            }
            set
            {
                this.nbrTentativeField = value;
            }
        }

        /// <remarks/>
        public string codeAgentRecenceur
        {
            get
            {
                return this.codeAgentRecenceurField;
            }
            set
            {
                this.codeAgentRecenceurField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("menages")]
        public MenageType[] menages
        {
            get
            {
                return this.menagesField;
            }
            set
            {
                this.menagesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    [System.Xml.Serialization.XmlRootAttribute("RapportSupervisionDirect", Namespace = "http://www.ihsi.ht/RGPHService/schema", IsNullable = false)]
    public partial class RapportSuperviseurDirectType
    {

        private long rapportIdField;

        private int codeAgentRecenseurField;

        private string codeSuperviseurField;

        private string codeDistrictField;

        private string comIdField;

        private string deptIdField;

        private short q1Field;

        private short q2Field;

        private short q3Field;

        private short q4Field;

        private short q5Field;

        private short q6Field;

        private short q7Field;

        private short q8Field;

        private short q9Field;

        private short q10Field;

        private short q11Field;

        private short q12Field;

        private short q13Field;

        private string q14Field;

        private short q15Field;

        private short scoreField;

        private System.DateTime dateEvaluationField;

        private int repportSenderIdField;

        /// <remarks/>
        public long rapportId
        {
            get
            {
                return this.rapportIdField;
            }
            set
            {
                this.rapportIdField = value;
            }
        }

        /// <remarks/>
        public int codeAgentRecenseur
        {
            get
            {
                return this.codeAgentRecenseurField;
            }
            set
            {
                this.codeAgentRecenseurField = value;
            }
        }

        /// <remarks/>
        public string codeSuperviseur
        {
            get
            {
                return this.codeSuperviseurField;
            }
            set
            {
                this.codeSuperviseurField = value;
            }
        }

        /// <remarks/>
        public string codeDistrict
        {
            get
            {
                return this.codeDistrictField;
            }
            set
            {
                this.codeDistrictField = value;
            }
        }

        /// <remarks/>
        public string comId
        {
            get
            {
                return this.comIdField;
            }
            set
            {
                this.comIdField = value;
            }
        }

        /// <remarks/>
        public string deptId
        {
            get
            {
                return this.deptIdField;
            }
            set
            {
                this.deptIdField = value;
            }
        }

        /// <remarks/>
        public short q1
        {
            get
            {
                return this.q1Field;
            }
            set
            {
                this.q1Field = value;
            }
        }

        /// <remarks/>
        public short q2
        {
            get
            {
                return this.q2Field;
            }
            set
            {
                this.q2Field = value;
            }
        }

        /// <remarks/>
        public short q3
        {
            get
            {
                return this.q3Field;
            }
            set
            {
                this.q3Field = value;
            }
        }

        /// <remarks/>
        public short q4
        {
            get
            {
                return this.q4Field;
            }
            set
            {
                this.q4Field = value;
            }
        }

        /// <remarks/>
        public short q5
        {
            get
            {
                return this.q5Field;
            }
            set
            {
                this.q5Field = value;
            }
        }

        /// <remarks/>
        public short q6
        {
            get
            {
                return this.q6Field;
            }
            set
            {
                this.q6Field = value;
            }
        }

        /// <remarks/>
        public short q7
        {
            get
            {
                return this.q7Field;
            }
            set
            {
                this.q7Field = value;
            }
        }

        /// <remarks/>
        public short q8
        {
            get
            {
                return this.q8Field;
            }
            set
            {
                this.q8Field = value;
            }
        }

        /// <remarks/>
        public short q9
        {
            get
            {
                return this.q9Field;
            }
            set
            {
                this.q9Field = value;
            }
        }

        /// <remarks/>
        public short q10
        {
            get
            {
                return this.q10Field;
            }
            set
            {
                this.q10Field = value;
            }
        }

        /// <remarks/>
        public short q11
        {
            get
            {
                return this.q11Field;
            }
            set
            {
                this.q11Field = value;
            }
        }

        /// <remarks/>
        public short q12
        {
            get
            {
                return this.q12Field;
            }
            set
            {
                this.q12Field = value;
            }
        }

        /// <remarks/>
        public short q13
        {
            get
            {
                return this.q13Field;
            }
            set
            {
                this.q13Field = value;
            }
        }

        /// <remarks/>
        public string q14
        {
            get
            {
                return this.q14Field;
            }
            set
            {
                this.q14Field = value;
            }
        }

        /// <remarks/>
        public short q15
        {
            get
            {
                return this.q15Field;
            }
            set
            {
                this.q15Field = value;
            }
        }

        /// <remarks/>
        public short score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dateEvaluation
        {
            get
            {
                return this.dateEvaluationField;
            }
            set
            {
                this.dateEvaluationField = value;
            }
        }

        /// <remarks/>
        public int repportSenderId
        {
            get
            {
                return this.repportSenderIdField;
            }
            set
            {
                this.repportSenderIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ihsi.ht/RGPHService/schema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.ihsi.ht/RGPHService/schema", IsNullable = false)]
    public partial class RapportDeroulementCollecte
    {

        private long detailsRapportIdField;

        private string districtIdField;

        private string codeSuperviseurField;

        private string dateRapportField;

        private RapportDeroulementCollecteType[] detailsRapportField;

        /// <remarks/>
        public long detailsRapportId
        {
            get
            {
                return this.detailsRapportIdField;
            }
            set
            {
                this.detailsRapportIdField = value;
            }
        }

        /// <remarks/>
        public string districtId
        {
            get
            {
                return this.districtIdField;
            }
            set
            {
                this.districtIdField = value;
            }
        }

        /// <remarks/>
        public string codeSuperviseur
        {
            get
            {
                return this.codeSuperviseurField;
            }
            set
            {
                this.codeSuperviseurField = value;
            }
        }

        /// <remarks/>
        public string dateRapport
        {
            get
            {
                return this.dateRapportField;
            }
            set
            {
                this.dateRapportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detailsRapport")]
        public RapportDeroulementCollecteType[] detailsRapport
        {
            get
            {
                return this.detailsRapportField;
            }
            set
            {
                this.detailsRapportField = value;
            }
        }
    }
}
